name: Java CI/CD with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Delete target folder
      run: rm -rf target

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Install Maven
      run: |
          # Download and install Maven
          wget -q https://apache.osuosl.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
          tar xf apache-maven-3.8.4-bin.tar.gz
          export PATH=$PATH:$(pwd)/apache-maven-3.8.4/bin
          mvn --version

    - name: Build and Install
      run: mvn clean install

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Docker
      run: |
        # Your Docker deployment commands here
        # For example, you can use Docker CLI to build and push the image

        docker build -t your-image-name .
        docker tag your-image-name:latest your-docker-registry/your-image-name:latest
        docker push your-docker-registry/your-image-name:latest